# See https://pre-commit.com/ for documentation
# For installation:
# - install via
#   pip install pre-commit
# - activate via
#   pre-commit install
# Now the below hooks will run at any invocation of
#  git commit
# To check all files in the repositoy run
#  pre-commit run --all-files
fail_fast: true
exclude: \.nb$|\.m$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: trailing-whitespace
        types: [text]
        exclude: \.dat$|\.in$
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=pylintrc", # Link to your config file
            "--disable=line-too-long,wildcard-import,unused-wildcard-import,missing-module-docstring,missing-function-docstring",
          ]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args:
          [
            "--config=setup.cfg", # Link to your config file
            "--ignore=E265,E266,E501,F401,F403,W503",
          ]
