fail_fast: true
exclude: \.nb$|\.m$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: trailing-whitespace
        types: [text]
        exclude: \.dat$|\.in$
