# See https://pre-commit.com/ for documentation
# For installation:
# - install via
#   pip install pre-commit
# - activate via
#   pre-commit install
# Now the below hooks will run at any invocation of
#  git commit
# To check all files in the repositoy run
#  pre-commit run --all-files
exclude: \.nb$|\.m$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        types: [text]
        exclude: \.dat$|\.in$
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
#       args: ["--severity=warning"]  # Optionally only show errors and warnings
# - repo: https://github.com/thclark/pre-commit-sphinx
#   rev: 0.0.3
#   hooks:
#     - id: build-docs
#       args: ['--cache-dir', 'docs/doctrees', '--html-dir', 'docs/_build/html', '--source-dir', 'docs/']
#       language_version: python3
#       additional_dependencies: [sphinx, sphinx-autoapi]
  - repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: ["--py311-plus"]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.11
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args:
          [
            "--settings=setup.cfg", # Link to your config file
            "--line-length=120",
            "--profile=black",
            "--force-grid-wrap=2",
            "--multi-line=3",
          ]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args:
          [
            "--config=setup.cfg", # Link to your config file
            # E265 block comment should start with '# '
            # E266 too many leading '#' for block comment
            # W503 line break before binary operator
            "--ignore=E265,E266,W503,",
            "--max-line-length=120",
            "--exclude=.git,__pycache__",
            "--select=C,E,F,W,B,B9",
          ]
      - id: pycodestyle
        name: pycodestyle
        entry: pycodestyle
        language: system
        types: [python]
        args:
          [
            "--config=setup.cfg", # Link to your config file
            # E203 whitespace before ‘,’, ‘;’, or ‘:’ - falsely triggers on list slices
            # E265 block comment should start with '# '
            # E266 too many leading '#' for block comment
            # W503 line break before binary operator
            "--ignore=E203,E265,E266,W503,",
            "--max-line-length=120",
            "--exclude=.git,__pycache__",
          ]
      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        types: [python]
        args:
          [
            "--config=setup.cfg", # Link to your config file
            "--convention=numpy",
          ]
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=pylintrc", # Link to your config file
            # C0302 too many lines
            # C0325 superfluous-parens
            # R0801 duplicate-code
            # R0912 too-many-branches
            # R0913 too-many-arguments
            # R0914 too-many-locals
            # R0915 too-many-statements
            # W0511 fixme
            "--disable=C0302,C0325,R0801,R0912,R0913,R0914,R0915,W0511,",
            "--max-line-length=120",
            "--ignore=.git,__pycache__",
          ]
      - id: mypy
        name: mypy
        pass_filenames: false  # suppress the normal filename passing
        entry: mypy .
        verbose: true
        language: system
        types: [python]
        args:
          [
            "--config-file=setup.cfg", # Link to your config file
            "--exclude=(.git|__pycache__)",
          ]
