#!/bin/bash

# Script the modifies the bash prompt to display free RAM, BATTERY-PERCENTAGE (if ~./IsLaptop exists), and CPU utilization.
# It also displays git information when git is installed and the current directory is part of a git repository.
# It is called by ~/.profile

if [ -f /usr/lib/git-core/git-sh-prompt ]; then
  source /usr/lib/git-core/git-sh-prompt
  GIT_PS1_SHOWDIRTYSTATE=1
  GIT_PS1_SHOWSTASHSTATE=1
  GIT_PS1_SHOWUNTRACKEDFILES=1
  GIT_PS1_SHOWUPSTREAM="auto"
  GIT_PS1_SHOWCOLORHINTS=1

  if [ -f ~/.IsLaptop ]; then
    PROMPT_COMMAND=initlaptop
    PS1='\[\033[47;30m\]RAM free: ${RAM} | CPU: ${CPU} | GPU: ${GPU} | Battery: ${BAT} \u@\h ($(uname -r)) \w$(__git_ps1 " (%s)")\[\033[0m\]\n\$ '
  else
    PROMPT_COMMAND=init
    PS1='\[\033[47;30m\]RAM free: ${RAM} | CPU: ${CPU} | GPU: ${GPU} | \u@\h ($(uname -r)) \w$(__git_ps1 " (%s)")\[\033[0m\]\n\$ '
  fi
else
  if [ -f ~/.IsLaptop ]; then
    PROMPT_COMMAND=initlaptop
    PS1='\[\033[47;30m\]RAM free: ${RAM} | CPU: ${CPU} | GPU: ${GPU} | Battery: ${BAT} \u@\h ($(uname -r)) \w\[\033[0m\]\n\$ '
  else
    PROMPT_COMMAND=init
    PS1='\[\033[47;30m\]RAM free: ${RAM} | CPU: ${CPU} | GPU: ${GPU} | \u@\h ($(uname -r)) \w\[\033[0m\]\n\$ '
  fi
fi

function promptRAM()
{
  RAM="$(free -h | awk 'NR==2 {print $4 "/" $2}')"
}

function promptCPU()
{
  read cpu a b c previdle rest < /proc/stat
  prevtotal=$((a+b+c+previdle))
  sleep 0.1
  read cpu a b c idle rest < /proc/stat
  total=$((a+b+c+idle))
  CPUUTIL="$((100 * ( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal)))%"
  CPUTEMP=""
  if [ "${HOSTNAME}" == "mykonos" ]; then
    CPUTEMP=", $(sensors | grep "CPU Temperature" | awk '{print $3}')"
  elif [ "${HOSTNAME}" == "dell01" ] || [ "${HOSTNAME}" == "dell02" ] || \
       [ "${HOSTNAME}" == "dell03" ] || [ "${HOSTNAME}" == "dell04" ] || \
       [ "${HOSTNAME}" == "smaug" ]; then
    CPUTEMP=", $(sensors | grep "CPU" | awk '{print $2}')"
  elif [ "${HOSTNAME}" == "max" ]; then
    CPUTEMP=", $(sensors | grep "Package id 0:" | awk '{print $4}')"
  fi
  CPU="${CPUUTIL}${CPUTEMP}"
}

function promptBAT()
{
  BAT="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep "percentage:" | awk '{print $2}')"
}

function promptGPU()
{
  GPU="---"
  if [ "${HOSTNAME}" == "max" ] && [ -x "$(command -v nvidia-smi)" ]; then
    GPUUTI="$(nvidia-smi --query-gpu="utilization.gpu" --format="csv,noheader" | awk '{print $1 "%"}')"
    GPUTMP="$(nvidia-smi --query-gpu="temperature.gpu" --format="csv,noheader")°C"
    GPUDRIVER="$(nvidia-smi -q | grep "Driver Version" | awk '{print $4}')"
    GPU="${GPUUTI}, ${GPUTMP} (${GPUDRIVER})"
  fi
}

function fetchgit()
{
# If we are in a git repository fetch in the background
if [ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" == "true" ]; then
  # If there is no instance of git fetch running
  if [ "$(pgrep -a git | grep 'git fetch')" == "" ]; then
    # () runs the command in a subshell to avoid the Done message due to the running in background
    (git fetch &)
  fi
fi
}

function init()
{
  promptRAM
  promptCPU
  promptGPU
  fetchgit
}

function initlaptop()
{
  promptRAM
  promptCPU
  promptBAT
  promptGPU
  fetchgit
}
